ctl.!default {
	type hw
	card sndi2s0
}
pcm.!default {
	type asym
	playback.pcm "PlaybackSPK"
	capture.pcm "CaptureMIC"
}

pcm.Playback {
    type plug
    slave.pcm {
        type softvol
        slave.pcm PlaybackDmix
        control {
            name "TX Soft Volume Master"
            card sndi2s0
        }
        min_dB -51.0
        max_dB 0.0
        resolution 256
    }
    slave.rate 48000
    slave.format S16_LE
}

pcm.PlaybackDmix {
    type plug
    slave.pcm {
        type dmix
        ipc_key 1111
        ipc_perm 0666
        slave {
            pcm "hw:sndi2s0"
            format S16_LE
            rate 44100
            channels 2
            period_size 960
            periods 8
        }
    }
}

pcm.PlaybackSPK {
	type hooks
	slave.pcm "Playback"
	hooks.0 {
	type ctl_elems
	hook_args [
		{
			name "OutputL Mixer DACL Switch"
			preserve true
			value 1
		}
		{
			name "OutputR Mixer DACR Switch"
			preserve true
			value 1
		}
		{
			name "LINEOUTL Switch"
			preserve true
			value 1
		}
		{
			name "LINEOUTR Switch"
			preserve true
			value 1
		}
		{
			name "SPK Switch"
			preserve true
			value 1
		}
		{
			name "SPK Volume"
			preserve true
			value 16
		}
	]
	}
}

pcm.PlaybackHP {
	type hooks
	slave.pcm "Playback"
	hooks.0 {
        type ctl_elems
        hook_args [
            {
                name "OutputR Mixer DACR Switch"
                preserve true
                value 1
            }
            {
                name "OutputL Mixer DACL Switch"
                preserve true
                value 1
            }
            {
                name "HPOUTL Switch"
                preserve true
                value 1
            }
            {
                name "HPOUTR Switch"
                preserve true
                value 1
            }
            {
                name "SPK Switch"
                preserve true
                value 0
            }
        ]
	}
}

pcm.CaptureDsnoop {
    type plug
    slave.pcm {
        type dsnoop
        ipc_key 2222
        ipc_perm 0666
        slave {
            pcm "hw:sndi2s0"
            rate 16000
            channels 2
            period_size 640
            periods 4
        }
    }
}

pcm.Capture {
    type plug
    slave.pcm {
        type softvol
        slave.pcm "CaptureDsnoop"
        control {
            name "RX Soft Volume Master"
            card sndi2s0
        }
        min_dB -51.0
        max_dB 0.0
        resolution 256
    }
}

pcm.CaptureMIC {
	type hooks
	slave.pcm "Capture"
	hooks.0 {
	type ctl_elems
	hook_args [
		{
			name "MIC1 Switch"
			preserve true
			value 1
		}
		{
			name "MIC2 Switch"
			preserve true
			value 1
		}
		{
			name "InputL Mixer MIC1 Switch"
			preserve true
			value 1
		}
		{
			name "InputR Mixer MIC2 Switch"
			preserve true
			value 1
		}
		{
			name "ADCL Gain"
			preserve true
			value 3
		}
		{
			name "ADCR Gain"
			preserve true
			value 3
		}
		{
			name "MIC1 Gain"
			preserve true
			value 3
		}
		{
			name "MIC2 Gain"
			preserve true
			value 3
		}
	]
	}
}

pcm.CaptureHP {
	type hooks
	slave.pcm "Capture"
	hooks.0 {
	type ctl_elems
	hook_args [
		{
			name "InputL Mixer LINEIN Switch"
			preserve true
			value 1
		}
		{
			name "LINEINL Switch"
			preserve true
			value 1
		}
		{
			name "LINEINR Switch"
			preserve true
			value 1
		}
		{
			name "ADCL Volume"
			preserve true
			value 172
		}
		{
			name "ADCR Volume"
			preserve true
			value 172
		}
	]
	}
}
