SectionVerb {
	EnableSequence [
		cset "name='LINEOUTL Switch' off"
		cset "name='LINEOUTR Switch' off"
		cset "name='SPK Switch' off"
		cset "name='HPOUT Switch' off"
		cset "name='MIC1 Switch' off"
		cset "name='MIC2 Switch' off"
		cset "name='MIC3 Switch' off"
	]
}

SectionDevice."Speaker" {
	Comment "Internal speaker"

	ConflictingDevice [
		"Headphones"
	]

	EnableSequence [
		cset "name='LINEOUTL Switch' on"
		cset "name='LINEOUTR Switch' on"
		cset "name='SPK Switch' on"
	]

	DisableSequence [
		cset "name='LINEOUTL Switch' off"
		cset "name='LINEOUTR Switch' off"
		cset "name='SPK Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackVolume "LINEOUT Gain"
		PlaybackChannels "2"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	EnableSequence [
		cset "name='MIC1 Switch' on"
		cset "name='MIC2 Switch' on"
	]

	DisableSequence [
		cset "name='MIC1 Switch' off"
		cset "name='MIC2 Switch' off"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},0"
		CaptureVolume "ADC1 Gain"
		CaptureSwitch "MIC1 Switch"
		CaptureChannels "2"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	ConflictingDevice [
		"Speaker"
	]

	EnableSequence [
		cset "name='HPOUT Switch' on"
	]

	DisableSequence [
		cset "name='HPOUT Switch' off"
	]

	Value {
		PlaybackVolume "HPOUT Gain"
		PlaybackPriority 200
		PlaybackChannels "2"
		PlaybackPCM "hw:${CardId},0"
		JackControl "HP Jack"
	}
}
